name: google_places_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.4.0
  google_places_flutter: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
